core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.urls import re_path, include
from graphene_django.views import GraphQLView

urlpatterns = [
    re_path(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    re_path(
        r"^about/$",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),
    # User management
    re_path(r"^users/", include("users.urls", namespace="users")),
    re_path(r"^accounts/", include("allauth.urls")),
    # Third party apps here
    re_path(r"^comments/", include("django_comments.urls")),
    re_path(r"^graphql", GraphQLView.as_view(graphiql=True)),
    re_path(r"^markdownx/", include("markdownx.urls")),
    # Local apps here
    re_path(
        r"^notifications/",
        include("notifications.urls", namespace="notifications"),
    ),
    re_path(r"^articles/", include("articles.urls", namespace="articles")),
    re_path(r"^notebooks/", include("notebooks.urls", namespace="notebooks")),
    re_path(r"^news/", include("news.urls", namespace="news")),
    re_path(r"^messages/", include("messager.urls", namespace="messager")),
    re_path(r"^qa/", include("qa.urls", namespace="qa")),
    re_path(r"^search/", include("search.urls", namespace="search")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        re_path(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        re_path(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        re_path(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        re_path(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

notebooks/urls.py
from django.urls import re_path

from .views import (
    NotebooksListView,
    DraftsListView,
    CreateNotebookView,
    EditNotebookView,
    DetailNotebookView,
)

app_name = "Notebooks"
urlpatterns = [
    re_path(r"^$", NotebooksListView.as_view(), name="list"),
    re_path(r"^write-new-Notebook/$", CreateNotebookView.as_view(), name="write_new"),
    re_path(r"^drafts/$", DraftsListView.as_view(), name="drafts"),
    re_path(r"^edit/(?P<pk>\d+)/$", EditNotebookView.as_view(), name="edit_notebook"),
    re_path(r"^(?P<slug>[-\w]+)/$", DetailNotebookView.as_view(), name="notebook"),
]

qa/urls.py
from django.urls import re_path

import qa.views as views

app_name = "qa"
urlpatterns = [
    re_path(r"^$", views.QuestionListView.as_view(), name="index_noans"),
    re_path(r"^answered/$", views.QuestionAnsListView.as_view(), name="index_ans"),
    re_path(r"^indexed/$", views.QuestionsIndexListView.as_view(), name="index_all"),
    re_path(
        r"^question-detail/(?P<pk>\d+)/$",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    re_path(r"^ask-question/$", views.CreateQuestionView.as_view(), name="ask_question"),
    re_path(
        r"^propose-answer/(?P<question_id>\d+)/$",
        views.CreateAnswerView.as_view(),
        name="propose_answer",
    ),
    re_path(r"^question/vote/$", views.question_vote, name="question_vote"),
    re_path(r"^answer/vote/$", views.answer_vote, name="answer_vote"),
    re_path(r"^accept-answer/$", views.accept_answer, name="accept_answer"),
]

users/urls.py
from django.urls import path,re_path
from . import views

app_name = "users"
urlpatterns = [
    re_path(r"^$", view=views.UserListView.as_view(), name="list"),
    re_path(r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    re_path(r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    re_path(
        r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

notebooks/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
from slugify import slugify

from django_comments.signals import comment_was_posted
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from taggit.managers import TaggableManager


from notifications.models import Notification, notification_handler


class NotebookQuerySet(models.query.QuerySet):
    """Personalized queryset created to improve model usability"""

    def get_published(self):
        """Returns only the published items in the current queryset."""
        return self.filter(status="P")
    
    def get_drafts(self):
        """Returns only the items marked as DRAFT in the current queryset."""
        return self.filter(status="D")

    def get_counted_tags(self):
        tag_dict = {}
        query = (
            self.filter(status="P").annotate(tagged=Count("tags")).filter(tags__gt=0)
        )
        for obj in query:
            for tag in obj.tags.names():
                if tag not in tag_dict:
                    tag_dict[tag] = 1

                else:  # pragma: no cover
                    tag_dict[tag] += 1

        return tag_dict.items()


class Notebook(models.Model):
    DRAFT = "D"
    PUBLISHED = "P"
    STATUS = ((DRAFT, _("Draft")), (PUBLISHED, _("Published")))

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="dev",
        on_delete=models.SET_NULL,
    )
    file = models.FileField(
        _("Le notebook"), upload_to="notebook/%Y/%m/%d/"
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, null=False, unique=True,verbose_name='Titre')
    description = models.TextField(max_length=255, null=True, verbose_name='Description')
    vue = models.FileField(
        _("Une version html du notebook pour l'affichage"), upload_to="notebook/%Y/%m/%d/",blank=True
    )
    slug = models.SlugField(max_length=80, null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    edited = models.BooleanField(default=False)
    tags = TaggableManager()
    objects = NotebookQuerySet.as_manager()

    class Meta:
        verbose_name = _("Notebook")
        verbose_name_plural = _("Notebooks")
        ordering = ("-timestamp",)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(
                f"{self.user.username}-{self.title}", lowercase=True, max_length=80
            )

        super().save(*args, **kwargs)

    def get_markdown(self):
        return markdownify(self.content)


def notify_comment(**kwargs):  # pragma: no cover
    """Handler to be fired up upon comments signal to notify the dev of a
    given Notebook."""
    actor = kwargs["request"].user
    receiver = kwargs["comment"].content_object.user
    obj = kwargs["comment"].content_object
    notification_handler(actor, receiver, Notification.COMMENTED, action_object=obj)


comment_was_posted.connect(receiver=notify_comment)

notebooks/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from .models import Notebook
from ckeditor.widgets import CKEditorWidget

class NotebookForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(
        widget=forms.HiddenInput(), required=False, initial=False
    )

    class Meta:
        model = Notebook
        fields = ["title", "file","vue","description", "tags", "status", "edited"]

notebooks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from helpers import AuthorRequiredMixin
from .models import Notebook
from .forms import NotebookForm


class NotebooksListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published Notebooks list."""

    model = Notebook
    paginate_by = 15
    context_object_name = "notebooks"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["popular_tags"] = Notebook.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Notebook.objects.get_published()


class DraftsListView(NotebooksListView):
    """Overriding the original implementation to call the drafts Notebooks
    list."""

    def get_queryset(self, **kwargs):
        return Notebook.objects.get_drafts()


class CreateNotebookView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new Notebooks."""

    model = Notebook
    message = _("Your Notebook has been created.")
    form_class = NotebookForm
    template_name = "notebooks/notebook_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("notebooks:list")


class EditNotebookView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing Notebooks."""

    model = Notebook
    message = _("Your Notebook has been updated.")
    form_class = NotebookForm
    template_name = "notebooks/notebook_update.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("notebooks:list")


class DetailNotebookView(LoginRequiredMixin, DetailView):
    """Basic DetailView implementation to call an individual Notebook."""

    model = Notebook

templates/notebooks/notebook_create.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'notebooks:list' %}">{% trans 'Notebooks' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Écrire un notebook' %}</li>
    </ol>
  </nav>
  <form action="{% url 'notebooks:write_new' %}" enctype="multipart/form-data"  id="notebook-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" id="publish" class="btn btn-primary publish">{% trans 'Publier' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Sauvegarder comme brouillon' %}</button>
      <a href="{% url 'notebooks:list' %}" class="btn btn-default">{% trans 'Annuler' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/notebooks.js' %}"></script>
{% endblock modal %}

templates/notebooks/notebook_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load comments crispy_forms_tags thumbnail humanize %}

{% block title %}{{ notebook.title|title }}{% endblock %}

{% block content %}
  <!-- Page Content -->
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'notebooks:list' %}">{% trans 'notebooks' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ notebook.title|title }}</li>
      </ol>
    </nav>
    <div class="row">
      <!-- Post Content Column -->
      <div class="col-lg-8" style="background:white;">
        <!-- Title -->
        <h1 class="mt-4">{{ notebook.title|title }}</h1>
        <!-- dev -->
        <p class="lead">{% trans 'by' %}
          <a href="{% url 'users:detail' notebook.user.username %}">{{ notebook.user.get_profile_name|title }}</a>
        </p>
        <hr>
        <!-- Date/Time -->
        <p>{% trans 'Posté' %} {{ notebook.timestamp|naturaltime }}  </p>
        <hr>
        <h5>Description:</h5>
        <hr>
        <p>{{notebook.description}}</p>
        <hr>
        <!-- Featured Image -->
        {% if notebook.vue %}
        <p >Voir le notebook: <a href="{{notebook.vue.url}}" target="_blank">Lien</a></p>          
        {% else %}
        <p class="card-text">Pas de preview fournit, désolé.</p>
        {% endif %}
        <!-- <img src="{{ MEDIA_URL }}{{ notebook.image }}" lt="{% trans 'Featured Image' %}" class="card-img-top"> -->
        <hr>
        <p >Télécharger le notebook: <a href="{{ notebook.file.url }}">Lien</a></p>
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Leave a Comment' %}:</h5>
          <div class="card-body" style="background: gray;">
            {% if user.is_authenticated %}
              {% get_comment_form for notebook as form %}
              <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form.comment|as_crispy_field }}
                {{ form.honeyspot }}
                {{ form.content_type }}
                {{ form.object_pk }}
                {{ form.timestamp }}
                {{ form.security_hash }}
                <input type="hidden" name="next" value="{% url 'notebooks:notebook' notebook.slug %}" />
                <input type="submit" value="{% trans 'Commenter' %}" id="id_submit" />
              </form>
            {% endif %}
          </div>
        </div>

        <!-- Single Comment -->

        {% get_comment_list for notebook as comment_list %}
        {% for comment in comment_list %}
          <div class="media mb-4">
            {% thumbnail comment.user.picture "x50" as im %}
              <img class="d-flex mr-3 rounded-circle" src="{{ im.url }}" alt="{% trans 'Picture Profile' %}" id="pic" />
            {% empty %}
              <img class="d-flex mr-3 rounded-circle" src="{% static 'img/user.png' %}" height="50px" alt="{% trans 'No Profile Picture' %}" />
            {% endthumbnail %}
            <div class="media-body">
              <h5 class="mt-0">{{ comment.user.get_profile_name|title }}</h5>
              {{ comment.comment|linebreaks }}
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Write notebook Widget -->
        {% if request.user.is_authenticated %}
          <div class="card my-4">
            <div class="card-body text-center">
              <a class="btn btn-success" href="{% url 'notebooks:write_new' %}" title="{% trans 'Écrire un notebook' %}"><i class="fa fa-pencil" aria-hidden="true"></i> {% trans 'New notebook' %}</a>
              <a class="btn btn-primary" href="{% url 'notebooks:edit_notebook' notebook.id %}" title="{% trans 'Éditer cet notebook' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Edit' %}</a>
            </div>
          </div>
        {% endif %}
        <!-- Cloud Tag Widget -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Tags' %}</h5>
          <div class="card-body">
            {% for tag in notebook.tags.all %}
              <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
{% endblock content %}

templates/notebooks/notebook_list.html
{% extends 'base.html' %}
{% load static i18n %}
{% load humanize thumbnail %}

{% block title %} {% trans 'notebooks' %} {% endblock %}

{% block head %}

{% endblock head %}

{% block content %}

  <!-- Page Content -->
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'notebooks:list' %}">{% trans 'notebooks' %}</a></li>
      </ol>
    </nav>
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8">
        {{context}}
        {% for notebook in notebooks %}
          <!-- Blog Post -->
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">{{ notebook.title|title }}</h2>
              <p>{{notebook.description}}</p>
              <h5>Téléchargement: <a href="{{notebook.file.url}}">{{notebook.title}}</a></h5>
              <a href="{% url 'notebooks:notebook' notebook.slug %}" class="btn btn-primary">{% trans 'Voir plus' %} &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              {% trans 'Posté' %} {{ notebook.timestamp|naturaltime }}
              <i class="lead fa fa-user"></i>
              <a href="{% url 'users:detail' notebook.user.username %}">{{ notebook.user.get_profile_name|title }}</a>
              {% for tag in notebook.tags.names %}
                <a href="#">{{ tag }}</a>
              {% endfor %}
            </div>
          </div>
        {% empty %}
          <h4 class="no-data">{% trans "Il n'y a pas encore de notebook." %}. <a href="{% url 'notebooks:write_new' %}">{% trans 'Soyez le premier à en publier un !' %}!</a></h4>
        {% endfor %}

        {% if is_paginated %}
          <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Newer' %}</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Older' %} &rarr;</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
            {% endif %}
          </ul>
        {% endif %}

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">
        <!-- Write notebook Widget -->
        {% if request.user.is_authenticated %}
          <div class="card my-4">
            <div class="card-body text-center">
              <a class="btn btn-success" href="{% url 'notebooks:write_new' %}" title="{% trans 'Écrire un nouvel notebook' %}"><i class="fa fa-pencil" aria-hidden="true"></i> {% trans 'Nouveau notebook' %}</a>
              <a class="btn btn-primary" href="{% url 'notebooks:drafts' %}" title="{% trans 'Brouillons' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Brouillons' %}</a>
            </div>
          </div>
        {% endif %}
        <!-- Cloud Tag Widget -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Tags' %}</h5>
          <div class="card-body">
            {% for tag, count in popular_tags %}
              <a href="#"><span class="badge badge-info">{{ count }} {{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

{% endblock content %}

templates/notebooks/notebook_update.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'notebooks:drafts' %}">{% trans 'Drafts' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Update an notebook' %}</li>
    </ol>
  </nav>
  <form action="{% url 'notebooks:edit_notebook' form.instance.pk %}" enctype="multipart/form-data"  id="notebook-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" class="btn btn-primary update">{% trans 'Update' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save as draft' %}</button>
      <a href="{% url 'notebooks:drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/notebooks.js' %}"></script>
{% endblock modal %}